# Generated by Django 3.1.1 on 2021-02-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='tracks',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
