# Generated by Django 3.1.1 on 2021-01-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
