# Generated by Django 3.1.1 on 2021-01-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('event', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
            ],
        ),
    ]
