# Generated by Django 3.1.1 on 2020-11-27 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_artist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Artists',
        ),
    ]
