# Generated by Django 3.1.1 on 2020-11-27 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201128_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='band',
            new_name='name',
        ),
    ]
