# Generated by Django 3.1.1 on 2020-11-27 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201128_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Artists',
            new_name='Artist',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='artist',
            new_name='artist_name',
        ),
        migrations.RenameField(
            model_name='band',
            old_name='name',
            new_name='band_name',
        ),
        migrations.AlterField(
            model_name='band',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.song'),
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
