# Generated by Django 3.1.1 on 2020-11-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201128_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='song',
        ),
    ]
