# Generated by Django 3.1.1 on 2020-12-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201202_2015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Track',
        ),
    ]
