# Generated by Django 3.1.1 on 2020-12-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_exportfoldername'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportfoldername',
            name='subject',
            field=models.CharField(default='export folder', max_length=125),
            preserve_default=False,
        ),
    ]
