# Generated by Django 3.1.1 on 2020-12-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_exportfoldername_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportFileName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=125)),
                ('name', models.CharField(max_length=125)),
            ],
        ),
    ]
