# Generated by Django 3.1.1 on 2020-12-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_exportfilename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportfilename',
            name='subject',
        ),
    ]
