# Generated by Django 3.1.1 on 2020-12-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_exportfilename_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExportFileName',
        ),
    ]
