# Generated by Django 3.1.1 on 2020-12-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_delete_exportfilename'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportFileName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
        ),
    ]
