# Generated by Django 3.1.1 on 2021-01-10 13:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_band_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.track'),
            preserve_default=False,
        ),
    ]
