# Generated by Django 3.1.1 on 2021-01-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_capital_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='capital',
        ),
        migrations.DeleteModel(
            name='Capital',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
