# Generated by Django 3.1.1 on 2021-01-10 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210110_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.track'),
            preserve_default=False,
        ),
    ]
