# Generated by Django 3.1.1 on 2021-01-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_band_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='track',
        ),
        migrations.AddField(
            model_name='band',
            name='tracks',
            field=models.ManyToManyField(to='app.Track'),
        ),
    ]
