# Generated by Django 3.1.1 on 2021-01-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210110_2006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audio',
            new_name='Song',
        ),
    ]
