# Generated by Django 3.1.1 on 2021-01-19 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
